### ISSUE TITLE
Make Linto speaking arbitrary text (TTS)

### ISSUE THREAD

**Issue by jerome83136** [linto-ai/linto-skills-core#6]
Hello,

I have an operational Linto stack, build on versions available ~1 week ago.

Now that Linto works, I started to play with Tock, Intents, Entities. Dictionnaries and custom skill nodes.
It works fine. Linto understands my custom intents and I'm able to send them for handling on my Home Automation Node-Red dedicated instance.

For example: if I say "éteins la lumière de la cuisine", I configured Linto to send this output to my HA Node-Red: (with the HTTP request node)

[...]
```

"body": {
  "topic": "blk/tolinto/raspberry1/nlp/file/92e2414fcdd",
  "conversationData": {
    
  },
  "transcript": {
    "text": "éteins la lumière de la cuisine",
    "confidence": 0
  },
  "nlu": {
    "intent": "eclairage",
    "entitiesNumber": 2,
    "entities": [
      {
        "start": 0,
        "end": 6,
        "entity": "actionlumiere",
        "evaluated": false,
        "subEntities": [       
        ],
        "probability": 1,
        "mergeSupport": false,
        "value": "éteins"
      },
      {
        "start": 24,
        "end": 31,
        "entity": "piece",
        "evaluated": false,
        "subEntities": [
          
        ],
        "probability": 1,
        "mergeSupport": false,
        "value": "cuisine"
      }
    ]
  }
}
```
[...]

Later I can process the body with my HA Node-Red and extract:
- intent: eclairage
- entities:
  - piece: cuisine
  - actionlumiere: éteins

Extracted data will then allow me to push the required action from Node-Red, to my HA MQTT server; resulting in the kitchen light being shut down in this case.

The problem is that Linto is unable to use TTS to give me a feedback in response to my custom intents.

For example, I would like Linto to say "Cuisine éteinte" in response to my "éteins la lumière de la cuisine" intent.

I have seen this kind of messages in the central Linto MQTT instance, when Linto replies to a "core" intent:

`{"behavior":{"say":{"phonetic":"Bonjour, je suis votre assistant vocal. Pour connaitre mais commandes vous pouvez me demander : que sais tu faire","text":"Bonjour, je suis votre assistant vocal. Pour connaître mes commandes vous pouvez me demander : que sais tu faire"}},"transcript":"bonjour nice bonjour"}`

But I don't really now where it comes from.

### My question follows:
How can I inject arbitrary text, in order to get the Linto client speaking it via TTS ?

I've seen there are some skill nodes to manage TTS, but I don't really understand how to use them.

I think I will require 2 things in order to address my use case:
- A way to inject a **text message** to the central Linto MQTT topic, dedicated to Linto clients TTS feedback
  (but what topic should I target ?)
- A way to route the **text message** to the Linto client that should speak the message over TTS (if I speak to clientA, then clientA should answer and not clientB)
  (Refering to documentation, I guess this routing is achieved by putting the "toSay" message in the topic dedicated to the target Client)

Or maybe is there some kinf of API, exposed by Linto clients or by the services stack, which I could use to handle TTS feedback on target clients ?

Do you have any tips to help me achieving this ?
Thank you for your help

Best regards

**Comment by Houpert** [comment]
Hello,

At the moment we don't have any way to send a text to linto to just say it. (it's on the WIP branch, next)

You will need to  create a node similar to the chatbot. [chatbot](https://github.com/linto-ai/linto-skills-core/tree/next/linto-chatbot). The chatbot require a text input and will generate a text in output.

Then create a **function** node that will redirect to your skill on certain payload (payload.conversationData.text for example)
The chatbot documentation (topic and format) is not yet done, it's only on the development branch at the moment.

But i don't see any interest of sending a text to the server to send back the say the text on the client side just to say it, would it be more simple to just use the client TTS ?

Best regards

**Comment by Houpert** [comment]
Hello,

Regarding linto answer it sound like you have more than one skill in the workflow (you can remove the no desired skill)

Then the you will need to create your own skill to be able to custom linto answer [make my skill](https://doc.linto.ai/#/skills/devguide/make_my_skills)

Best regards

**Comment by jerome83136** [comment]
Hello,

I don't know how I missed this part of documentation.
I think I will be able to make what I want with this, thank you !
I will keep you up to date and close the issue as soon as it is working.

Best regards
